# Generated by Django 3.0 on 2021-02-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_games_game_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='game_sale',
        ),
        # migrations.RemoveField(
        #     model_name='games',
        #     name='game_valid',
        # ),
    ]
