# Generated by Django 3.0 on 2021-02-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_games_game_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['-game_published'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RemoveField(
            model_name='games',
            name='game_name',
        ),
    ]
